name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-docker-app:${{ github.sha }} . 

      - name: Push Docker Image to Docker Hub (Replace with your credentials)
        run: |
          docker login -u aswinth012 -p Zara$3362
          docker push my-docker-app:${{ github.sha }} 

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - name: Login to Server (Replace with your server details)
        run: |
           b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAvM51mKNx6X1sFTi62PGhlHfD4XcUc5L43lgEuBV7JQzwP7Cu5X/D
rKSmZx6msC5Ver7HIxgjwoIkwFBFVsLDMOsO/rEaz8sDRj+x7/5gKCnhQPctKEzh+WVJk1
llF6u+xKw5X3ZE/vDFL8LKh2XjnstBj9Wh8uP107yMQxPKh5IMxednYkv4yzwv23DgReN2
IE+RLDlaQrc2Q1V0KDqnTE9BLveRTp6D1t4Nd+7sE3dd/WAH4m1mqc6gHEjB8zMNrszV/F
LyBf2aH1TFsERQ5NrezjjSiD0DYgTQw6KGKkiX4ScJLo1sKvwS9D5ott9yIKrDG0epyawn
luBoOdP7wuemd0w3Pjl8MYX7G2srrwhCyeCk09q0lfCgWfKHBEI3gpskcg0T5rrBQb0sNI
s+1Hsn2C9zInRe2edC6hcVsSVbJseKQP6wXGZdfX4oQUbjUNkRcQ0w40whARF1hWgoNbk8
8yMnM5cw1/P3nCrs/H2ueG4dUKXtIGXLL/Eu9jUBAAAFkHyMtoJ8jLaCAAAAB3NzaC1yc2
EAAAGBALzOdZijcel9bBU4utjxoZR3w+F3FHOS+N5YBLgVeyUM8D+wruV/w6ykpmceprAu
VXq+xyMYI8KCJMBQRVbCwzDrDv6xGs/LA0Y/se/+YCgp4UD3LShM4fllSZNZZRervsSsOV
92RP7wxS/Cyodl457LQY/VofLj9dO8jEMTyoeSDMXnZ2JL+Ms8L9tw4EXjdiBPkSw5WkK3
NkNVdCg6p0xPQS73kU6eg9beDXfu7BN3Xf1gB+JtZqnOoBxIwfMzDa7M1fxS8gX9mh9Uxb
BEUOTa3s440og9A2IE0MOihipIl+EnCS6NbCr8EvQ+aLbfciCqwxtHqcmsJ5bgaDnT+8Ln
pndMNz45fDGF+xtrK68IQsngpNPatJXwoFnyhwRCN4KbJHINE+a6wUG9LDSLPtR7J9gvcy
J0XtnnQuoXFbElWybHikD+sFxmXX1+KEFG41DZEXENMONMIQERdYVoKDW5PPMjJzOXMNfz
95wq7Px9rnhuHVCl7SBlyy/xLvY1AQAAAAMBAAEAAAGANAoV2JHoMkp7EWhW+7ex6PmPuG
O5c9eFF8eb2V82V3J2/58DvcbW2I1zPgXxPKswrUnLGm2rYY+8cHNPgUfiQ+ft9J48/RwA
FYs10KfEuh089EqMnEiAmlxkCKSBnCIezReJIro27yvOtcjTSLl5IQn10p636foSBh+4az
6XuoEzWxLaaHn3I5E9wZadgjXdF6/GnDFcovnbj3iMsQ/lj79igH8FAm3necAvZyin0f+7
HLysv6iWvOPyNomJR66AtDIWIfFM8sQpeOsHhOW5POCY9N41L+0Bmdcdow5uO2AhrUBlvu
ZS4iO4ukbL6YYCpWiSzdD2/EEsZtomBH0njTxyYZHG8isze2GzN/V3KYSoyA+6BkEwWhO5
CbdpoJKrTpWOu1mZH7fQYpU8ByALtdsWTle4ynoIKQCkkyCIVHH51012x32XMgUO4LP0Kq
03qxAbLkmSoav1J413MSo/Ez/ddag8POz9+Lu6iAMhZtYNRpTpaB8hJ9WVMYL1rwgfAAAA
wDbuu+iZwjHerq3uHf6Zn4y+nB1zR57NQ42Hj374vWx76a2pi78DW/gTBtq8tD3H5oblw1
JXNoImMtssnNy2ZEO3tERtSbNhe5KIcO9epyxZQ0j8ilb+GAPTS/gIeSPKKMB9znD9OjTt
FRbqsbyHBd8q65/vuDW1qtc90I8p10gbjQliK1Eqhwr1ReMucILzQwUslNeqg+MNrrYAul
/mXqYghuObI6OQobtuSICRo+8Rh/T4+QuOnBPpGd5eOUrtSwAAAMEA47MsJ6+utsvSkge3
SHO7x6XhHWM7cjcgPcSLFKQh9qfCqjyYd37pKk8D0t48/ILrliNkY3/y0mV9TpF84x3ICg
5HkN0CnqUqXsZgnJeGExxgq1F36lrofLi6EN372RNyaTu3hXFBHfCfYARGWuAhKfa1twrF
k2eEuS/skOZ6hUXHIUnoFjiOV9yFH/G8IEb/L5oyaAVBjvmdNmBtryeUgWIXkJEAZKt/YU
/gO/4Nl8to9qFDqyWNh3CgAJRcozaHAAAAwQDURcxTTY7VCt+Ub8sU1wzYweo0VgoT2+bU
HHPE6s0itWORsBYQt16qYw26M5bjAFqk0K4OOhZex9fA8QmH28sVPrUhfOGskO4puIe3B/
u0oEqdeoEIGBG5DwoV2v4QKL3IW/EU4ahKoRowCxou5i5TsbA4DzK0O8ndW725T7xtREoA
yABFdHvq7PeY6UmpAxbTuDl74t5azDp1Go+FHCwVk6/TfD/50uZ+Ip/QvGOOkaGcRXEaxq
9b+nKMRDVwEjcAAAAWdWJ1bnR1QGlwLTE3Mi0zMS0zNy02MAECAwQF ubuntu@ip-172-31-37-60 

      - name: Deploy Container (Replace with your desired deployment method)
        run: |
          docker stop my-docker-app 
          docker rm my-docker-app 
          docker run -d -p 8080:8080 --name my-docker-app my-docker-app:${{ github.sha }}
