name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the 'main' branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-image:latest . 

      - name: Push Docker Image to Docker Hub (Optional)
        run: |
          docker login -u aswinth012 -p Zara$3362
          docker push my-image:latest 

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Kubernetes (Example)
        run: |
          kubectl apply -f kubernetes/deployment.yaml
